export default {
    CURRENCY_REQUEST: 'CURRENCY_REQUEST',
    CURRENCIES_LOADED_SUCCESS: 'CURRENCIES_LOADED_SUCCESS',
    CURRENCIES_LOADED_ERROR: 'CURRENCIES_LOADED_ERROR',
    ON_CHANGE_CURRENCY: 'ON_CHANGE_CURRENCY'
} 